name: 'Inflate Secrets'
description: 'Inflates the secret values into the appropriate files'
inputs:
  keystore:
    description: 'The keystore to inflate'
    required: true
  google-services:
    description: 'The google-services.json to inflate'
    required: true
  firebase-creds:
    description: 'The firebase credentials to inflate'
    required: true
  playstore-creds:
    description: 'The playstore credentials to inflate'
    required: true
outputs:
runs:
  using: 'composite'
  steps:
    - name: Mock debug google-services.json
      run: |
        cp .github/mock-google-services.json app/src/debug/google-services.json
        cp .github/mock-google-services.json app/src/minimal/google-services.json

    - name: Inflate release_keystore.keystore
      env:
        KEYSTORE: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
      run: echo $KEYSTORE | base64 --decode > app/release_keystore.keystore

    - name: Inflate google-services.json
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLESERVICES }}
      run: echo $GOOGLE_SERVICES > app/google-services.json

    - name: Inflate firebaseAppDistributionServiceCredentialsFile.json
      env:
        CREDS: ${{ secrets.FIREBASECREDS }}
      run: echo $CREDS > firebaseAppDistributionServiceCredentialsFile.json

    - name: Inflate playStorePublishServiceCredentialsFile.json
      env:
        CREDS: ${{ secrets.PLAYSTORECREDS }}
      run: echo $CREDS > app/playStorePublishServiceCredentialsFile.json