version: 2
updates:
  # Updates for Github Actions used in the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Gradle
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
