name: "Upload SARIF results"
description: "Merge and adjust the SARIF files to be compatible with GitHub Security Code Scanning and upload it to the GitHub Security tab."
inputs:
  category:
    description: "Category used to group the SARIF results."
    required: true
runs:
  using: "composite"
  steps:
    - name: Merge ${{ inputs.category }} report into one
      shell: bash
      if: ${{ !cancelled() && hashFiles('**/*.sarif') != '' }}
      run: python3 ./.github/scripts/merge_sarif.py

    - name: Upload SARIF results
      if: ${{ !cancelled() && hashFiles('merged_results.sarif') != '' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ inputs.category }}_sarif_results
        path: merged_results.sarif

    - name: Upload ${{ inputs.category }} reports (SARIF)
      if: ${{ !cancelled() && hashFiles('merged_results.sarif') != '' }}
      uses: github/codeql-action/upload-sarif@19b2f06db2b6f5108140aeb04014ef02b648f789 # v4.31.11
      with:
        sarif_file: "./merged_results.sarif"
        category: ${{ inputs.category }}
