name: 'Create Release Numbers'
description: 'Creates the current release number based on checked out code'
inputs:
  beta:
    description: 'If this is a beta build'
    required: true
    default: false
outputs:
  version-code:
    description: 'The numeric app version'
    value: ${{ steps.version-generator.outputs.version-code }}
runs:
  using: 'composite'
  steps:
    - name: Set Build Number
      id: version-generator
      shell: bash
      run: |
        COMMITS=`git rev-list --count HEAD`
        TAGS=`git tag | grep -v beta | wc -l`
        VC=$((((COMMITS+TAGS) * 3) << 1))
        echo Number Commits $COMMITS
        echo Number Tags $TAGS
        echo Version Code $VC
        echo "version-code=$VC" >> $GITHUB_OUTPUT
