name: "Create Release Notes"
description: "Creates the current releases release notes"
inputs:
  tag-name:
    description: "Name of the tag that will be used for this release"
    required: true
  gh-token:
    description: "The GitHub token used to get details from the API"
    required: true
runs:
  using: "composite"
  steps:
    - name: Get Previous Release Tag
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: latest-release-tag
      with:
        github-token: ${{ inputs.gh-token }}
        result-encoding: string
        script: |
          const { data } = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          return data.tag_name
    - name: Get Generated Release Notes
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: generate-notes
      env:
        TAG_NAME: ${{ inputs.tag-name }}
        PREVIOUS_TAG: ${{ steps.latest-release-tag.outputs.result }}
      with:
        github-token: ${{ inputs.gh-token }}
        result-encoding: string
        script: |
          const { data } = await github.rest.repos.generateReleaseNotes({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: process.env.TAG_NAME,
            target_commitish: 'main',
            previous_tag_name: process.env.PREVIOUS_TAG,
          })
          return data.body.replaceAll('`', '\'').replaceAll('"', '\'')
    - name: Generate Release Notes
      id: version-generator
      shell: bash
      env:
        PREVIOUS_TAG: ${{ steps.latest-release-tag.outputs.result }}
        CHANGELOG: ${{ steps.generate-notes.outputs.result }}
      run: |
        mkdir -p ./app/build/outputs/

        echo "Previous Release Tag:"
        echo "$PREVIOUS_TAG"

        echo "Full Changelog:"
        echo -e "$CHANGELOG"
        printf "%s" "$CHANGELOG" > ./app/build/outputs/changelogGithub

        echo "Beta Changelog:"
        git log --format="* %s" HEAD^..HEAD
        git log --format="* %s" HEAD^..HEAD > ./app/build/outputs/changelogBeta
