name: 'Create Release Notes'
description: 'Creates the current releases release notes'
runs:
  using: 'composite'
  steps:
    - name: Generate Release Notes
      id: version-generator
      shell: bash
      run: |
        mkdir -p ./app/build/outputs/
        
        echo "Previous Release Commit:"
        git tag -l --sort=-creatordate | grep -v beta- | head -n 1
        previous=`git tag -l --sort=-creatordate | grep -v beta- | head -n 1`
        
        echo "# Changes:" > ./app/build/outputs/changelogGithub
        echo "Changlog:"
        git log --format="* %s" ${previous}..HEAD
        git log --format="* %s" ${previous}..HEAD >> ./app/build/outputs/changelogGithub

        echo "Beta Changelog"
        git log --format="* %s" HEAD^..HEAD
        git log --format="* %s" HEAD^..HEAD > ./app/build/outputs/changelogBeta
