name: 'Create Release Notes'
description: 'Creates the current releases release notes'
inputs:
  tag-name:
    description: 'Name of the tag that will be used for this release'
    required: true
  gh-token:
    description: 'The GitHub token used to get details from the API'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get Previous Release Tag
      uses: actions/github-script@v6
      id: release-tag
      with:
        github_token: ${{ inputs.gh-token }}
        script: |
          return await github.rest.repos.getLatestRelease({
            home-assistant,
            android
          })
    - name: Get Generated Release Notes
      uses: actions/github-script@v6
      id: generate-notes
      with:
        github_token: ${{ inputs.gh-token }}
        script: |
          return await github.rest.repos.generateReleaseNotes({
            home-assistant,
            android,
            ${{inputs.tag_name}},
            master,
            ${{steps.release-tag.outputs.result.tag_name}},
          })
    - name: Generate Release Notes
      id: version-generator
      shell: bash
      run: |
        mkdir -p ./app/build/outputs/
        
        echo "Previous Release Tag:"
        echo "${{steps.release-tag.outputs.result.tag_name}}"
        
        echo "Full Changelog:"
        CHANGELOG="${{steps.generate-notes.outputs.result.body}}"
        echo -e $CHANGELOG
        printf "$CHANGELOG" > ./app/build/outputs/changelogGithub

        echo "Beta Changelog:"
        git log --format="* %s" HEAD^..HEAD
        git log --format="* %s" HEAD^..HEAD > ./app/build/outputs/changelogBeta
