name: 'Create Release Notes'
description: 'Creates the current releases release notes'
inputs:
  tag-name:
    description: 'Name of the tag that will be used for this release'
    required: true
  gh-token:
    description: 'The GitHub token used to get details from the API'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate Release Notes
      id: version-generator
      shell: bash
      run: |
        mkdir -p ./app/build/outputs/
        
        echo "Previous Release Tag:"
        TAG=`\
          curl --no-progress-meter --request GET \
            --url "https://api.github.com/repos/home-assistant/android/releases/latest" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{inputs.gh-token}}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
         | jq -r .tag_name
        `
        echo $TAG
        
        echo "Full Changelog:"
        CHANGELOG=`\
          curl --no-progress-meter --request POST \
            --url "https://api.github.com/repos/home-assistant/android/releases/generate-notes" \
            --header "Accept: application/vnd.github+json" \
            --header "Authorization: Bearer ${{inputs.gh-token}}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --data "{\"tag_name\":\"${{inputs.tag-name}}\",\"target_commitish\":\"master\",\"previous_tag_name\":\"$TAG\"}" \
         | jq -r .body
        `
        echo -e $CHANGELOG
        printf "$CHANGELOG" > ./app/build/outputs/changelogGithub

        echo "Beta Changelog:"
        git log --format="* %s" HEAD^..HEAD
        git log --format="* %s" HEAD^..HEAD > ./app/build/outputs/changelogBeta
