name: "Setup build environment"
description: "Setup the runner with all the tools we need to build our project."
inputs:
    mock-google-services:
        description: "Mock the google-services.json file inside the gradle modules."
        default: "false"
        required: false
runs:
    using: "composite"
    steps:
        - name: Mock google-services.json
          shell: bash
          if: ${{ inputs.mock-google-services == 'true' }}
          run: |
              cp .github/mock-google-services.json app/google-services.json
              cp .github/mock-google-services.json wear/google-services.json
              cp .github/mock-google-services.json automotive/google-services.json

        - name: Set up JDK 17
          uses: actions/setup-java@v4.7.0
          with:
              distribution: "temurin"
              java-version: "17"

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4
