name: "Setup build environment"
description: "Setup the runner with all the tools we need to build our project."
inputs:
  mock-google-services:
    description: "Mock the google-services.json file inside the gradle modules."
    default: "false"
    required: false
  cache-disabled:
    description: When 'true', all caching is disabled. No entries will be written to or read from the cache.
    required: false
    default: "false"
  cache-encryption-key:
    description: "The key used to encrypt the cache. This is a secret and should not be exposed."
    required: true
runs:
  using: "composite"
  steps:
    - name: Mock google-services.json
      shell: bash
      if: ${{ inputs.mock-google-services == 'true' }}
      run: |
        cp .github/mock-google-services.json app/google-services.json
        cp .github/mock-google-services.json wear/google-services.json
        cp .github/mock-google-services.json automotive/google-services.json

    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.1
      with:
        distribution: "temurin"
        java-version: "21"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: ${{ inputs.cache-disabled == 'true'}}
        cache-encryption-key: ${{ inputs.cache-encryption-key}}
