default_config:

logger:
  default: info
  logs:
    aiohttp.access: info
    homeassistant.components.http: debug
    homeassistant.components.mobile_app: debug
    homeassistant.components.websocket_api: debug
