complexity:
  LongParameterList:
    ignoreAnnotated:
      - Composable
  TooManyFunctions:
    ignoreAnnotatedFunctions:
      - Preview

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MaxLineLength:
    active: false
  UnusedPrivateFunction:
    ignoreAnnotated:
      - Preview
