package io.homeassistant.companion.android.sensors

import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.ElementsIntoSet
import io.homeassistant.companion.android.common.sensors.SensorManager
import io.homeassistant.companion.android.sensorcatalog.generated.GeneratedSensorCatalogWear

/**
 * Contributes the `:wear` module's `@CatalogSensor` sensors into the `Set<BasicSensor>` catalog.
 *
 * Hand-written for the same reason as [io.homeassistant.companion.android.common.sensors.CommonSensorCatalogModule]:
 * Hilt does not aggregate an `@InstallIn` module generated by another KSP processor, so the
 * processor emits only the [GeneratedSensorCatalogWear] data object and this source module binds it.
 */
@Module
@InstallIn(SingletonComponent::class)
internal object WearSensorCatalogModule {
    @Provides
    @ElementsIntoSet
    fun wearCatalogSensors(): Set<SensorManager.BasicSensor> = GeneratedSensorCatalogWear.sensors
}
