package io.homeassistant.companion.android.sensors

import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import dagger.multibindings.ElementsIntoSet
import io.homeassistant.companion.android.common.sensors.SensorManager
import io.homeassistant.companion.android.sensorcatalog.generated.GeneratedSensorCatalogApp

/**
 * Contributes the `:app` module's `@CatalogSensor` sensors into the `Set<BasicSensor>` catalog.
 *
 * Hand-written for the same reason as [io.homeassistant.companion.android.common.sensors.CommonSensorCatalogModule]:
 * Hilt does not aggregate an `@InstallIn` module generated by another KSP processor, so the
 * processor emits only the [GeneratedSensorCatalogApp] data object and this source module binds it.
 *
 * `:automotive` reuses this source set, so it must also generate `GeneratedSensorCatalogApp` (its
 * `catalogModuleSuffix` is set to `app`).
 */
@Module
@InstallIn(SingletonComponent::class)
internal object AppSensorCatalogModule {
    @Provides
    @ElementsIntoSet
    fun appCatalogSensors(): Set<SensorManager.BasicSensor> = GeneratedSensorCatalogApp.sensors
}
