name: On Push

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      beta:
        description: "true if this is a beta release"
        required: false
        default: "false"
  push:
    branches:
      - main
      - wear-tls-review-comments

env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5

jobs:
  app_build:
    name: Github, Firebase, and Sentry Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup-build-env
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          mock-google-services: "true"

      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: "4.0.2"
          bundler-cache: false

      - uses: ./.github/actions/create-release-number
        name: Create Release Number
        id: rel_number

      - name: Generate dummy keystore
        run: |
          keytool -genkeypair -v \
          -alias androiddebugkey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -keystore /home/runner/work/android/android/ci_dummy_keystore.keystore \
          -dname "CN=Android CI dummy, O=Android, C=FR" \
          -storepass android \
          -keypass android

      - uses: ./.github/actions/download-translations
        name: Download Translations
        with:
          lokalise-project: ${{ secrets.LOKALISE_PROJECT }}
          lokalise-token: ${{ secrets.LOKALISE_TOKEN }}

      - name: Build Release
        env:
          KEYSTORE_PATH: /home/runner/work/android/android/ci_dummy_keystore.keystore
          KEYSTORE_ALIAS: androiddebugkey
          KEYSTORE_ALIAS_PASSWORD: android
          KEYSTORE_PASSWORD: android
          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
        run: |
          ./gradlew :common:assemble :app:assembleRelease :wear:assembleRelease :automotive:assembleRelease

      - name: Archive Build
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release-apks
          path: ./**/*.apk
