name: Production Deploy

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  release:
    types: [released]

env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5

permissions:
  contents: read

jobs:
  play_promote_production:
    name: Play Publish Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1.312.0
        with:
          ruby-version: "4.0.5"
          bundler-cache: false

      - uses: ./.github/actions/inflate-secrets
        name: Inflate Secrets
        with:
          keystore: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          google-services: ${{ secrets.GOOGLESERVICES }}
          firebase-creds: ${{ secrets.FIREBASECREDS }}
          playstore-creds: ${{ secrets.PLAYSTORECREDS }}

      - name: Install Fastlane dependencies
        run: bundle install

      - name: Promote Beta to Production Play Store
        run: bundle exec fastlane promote_to_production
